### ISSUE TITLE
[Material theme] Login form labels too narrow for Russian locale

### ISSUE THREAD

**Issue by K900** [openwrt/luci#1231]
Right now, the form looks like this when used with the Russian locale:

![](https://i.imgur.com/QQ2qkpz.png)

Making the labels wider produces a much nicer result:

```css
.node-main-login > .main .cbi-value-title {
    width: 10rem;
}
```

![](https://i.imgur.com/7UjclEs.png)
