### ISSUE TITLE
csstidy break font-face

### ISSUE THREAD

**Issue by jjm2473** [openwrt/luci#5067]
Say there is a test.css:
```css
@font-face {
  font-family: 'argon';

  src: url('fonts/argon.eot?vncylf#iefix') format('embedded-opentype'), url('fonts/argon.ttf?vncylf') format('truetype'), url('fonts/argon.woff?vncylf') format('woff'), url('fonts/argon.svg?vncylf#argon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
@font-face {
  font-family: 'TypoGraphica';
  src: url('fonts/TypoGraphica.eot?#iefix') format('embedded-opentype'), url('fonts/TypoGraphica.woff') format('woff'), url('fonts/TypoGraphica.ttf') format('truetype'), url('fonts/TypoGraphica.svg#TypoGraphica') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

run `./staging_dir/hostpkg/bin/csstidy test.css --remove_last_semicolon=true tmp.css`, got tmp.css:
```css
@font-face {
font-display:block;
font-family:TypoGraphica;
src:url(fonts/TypoGraphica.eot?#iefix) format('embedded-opentype'),url(fonts/TypoGraphica.woff) format('woff'),url(fonts/TypoGraphica.ttf) format('truetype'),url(fonts/TypoGraphica.svg#TypoGraphica) format('svg');
font-weight:400;
font-style:normal
}
```
